name: Build WhatsappUpdater

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet packages
      run: nuget restore WhatsappUpdater.sln

    - name: Setup .NET Framework 4.6.1 Developer Pack
      uses: microsoft/setup-dotnet@v3
      with:
        dotnet-version: '4.6.1'

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build solution
      run: msbuild WhatsappUpdater.sln /p:Configuration=Release

    - name: Upload artifact (Compiled EXE)
      uses: actions/upload-artifact@v4
      with:
        name: WhatsappUpdater-Build
        path: |
          **/bin/Release/**

