name: Build WhatsApp Desktop NoStore

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet packages
      run: nuget restore WhatsappUpdater.sln

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build solution
      run: msbuild WhatsappUpdater.sln/p:Configuration=Release

    - name: Upload artifact (Compiled EXE)
      uses: actions/upload-artifact@v4
      with:
        name: WhatsappUpdater-NoStore-Build
        path: |
          **/bin/Release/**
